title: "Heavenization World Peace Initiative"
description: "Resolving global conflicts through visionary solutions"
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
baseurl: ""
url: "https://thegrandresonance.org"

plugins:
  - jekyll-include-cache
  - jekyll-feed

header_pages:
  - index.md
